from pyspark.sql.types import *

def getDataSchema():
    data_schema = StructType([StructField("CallNumber", IntegerType(), True)
                            ,StructField("UnitID", StringType(), True)
                            ,StructField("IncidentNumber", IntegerType(), True)
                            ,StructField("CallType", StringType(), True)
                            ,StructField("WatchDate", StringType(), True)
                            ,StructField("ReceivedDtTm", StringType(), True)
                            ,StructField("EntryDtTm", StringType(), True)
                            ,StructField("DispatchDtTm", StringType(), True)
                            ,StructField("ResponseDtTm", StringType(), True)
                            ,StructField("OnSceneDtTm", StringType(), True)
                            ,StructField("TransportDtTm", StringType(), True)
                            ,StructField("HospitalDtTm", StringType(), True)
                            ,StructField("CallFinalDisposition", StringType(), True)
                            ,StructField("AvailableDtTm", StringType(), True)
                            ,StructField("Address", StringType(), True)
                            ,StructField("City", StringType(), True)
                            ,StructField("Zipcode", StringType(), True)
                            ,StructField("Battalion", StringType(), True)
                            ,StructField("StationArea", StringType(), True)
                            ,StructField("Box", StringType(), True)
                            ,StructField("OriginalPriority", StringType(), True)
                            ,StructField("Priority", StringType(), True)
                            ,StructField("FinalPriority", StringType(), True)
                            ,StructField("ALSUnit", StringType(), True)
                            ,StructField("CallType2", StringType(), True)
                            ,StructField("NumberOfAlarms", StringType(), True)
                            ,StructField("UnitType", StringType(), True)
                            ,StructField("UnitSequence", StringType(), True)
                            ,StructField("FirePrevention", StringType(), True)
                            ,StructField("Supervisor", StringType(), True)
                            ,StructField("Neighborhood", StringType(), True)
                            ,StructField("Location", StringType(), True)
                            ,StructField("RowID", StringType(), True)
                            ])
    return data_schema
